baseURL = "https://johnjim0816.github.io/" 
title = "My Hugo Blog"
theme = 'PaperMod'

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true  # 默认语言也走子路径就设为 true；想让中文在根 / 则设为 false
enableRobotsTXT = true

summaryLength = 40          # 默认 70（按单词或 CJK 字符统计）
hasCJKLanguage = true       # 中文/日文/韩文站点建议打开

[languages.zh]
    languageName = "中文"
    weight = 1
    title = "JJ's Blog"
[languages.en]
  languageName = "English"
  weight = 2
  title = "JJ's Blog"

[markup.goldmark.renderer]
  unsafe = true 

[permalinks]
  rl    = "/rl/:sections/:slug/"
  chore = "/chore/:slug/"

[params]
  mainSections = ["rl", "chore", "posts"]  # 让主题首页也列出这些 section