baseURL = "https://johnjim0816.github.io/" 
title = "My Hugo Blog"
theme = 'PaperMod'

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true  # é»˜è®¤è¯­è¨€ä¹Ÿèµ°å­è·¯å¾„å°±è®¾ä¸º trueï¼›æƒ³è®©ä¸­æ–‡åœ¨æ ¹ / åˆ™è®¾ä¸º false
enableRobotsTXT = true

summaryLength = 40          # é»˜è®¤ 70ï¼ˆæŒ‰å•è¯æˆ– CJK å­—ç¬¦ç»Ÿè®¡ï¼‰
hasCJKLanguage = true       # ä¸­æ–‡/æ—¥æ–‡/éŸ©æ–‡ç«™ç‚¹å»ºè®®æ‰“å¼€

[languages.zh]
    languageName = "ä¸­æ–‡"
    weight = 1
    title = "JJ's Blog"
[languages.en]
  languageName = "English"
  weight = 2
  title = "JJ's Blog"

[markup.goldmark.renderer]
  unsafe = true 

[permalinks]
  rl    = "/rl/:sections/:slug/"
  chore = "/chore/:slug/"

[params]
  mainSections = ["rl", "chore", "posts"]  # è®©ä¸»é¢˜é¦–é¡µä¹Ÿåˆ—å‡ºè¿™äº› section

[outputs]
  home = ["HTML","RSS","JSON"]
  
[languages.zh.menu]
  [[languages.zh.menu.main]]
    identifier = "search"
    name = "æœç´¢"
    url = "/search/"
    weight = 10
    pre = "ğŸ”"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"      # å¤§å¤šæ•°ä¸»é¢˜ä¼šåšè¯­è¨€ç›¸å¯¹é“¾æ¥
    weight = 10
    pre = "ğŸ”"
